# Generated by Django 3.1.3 on 2020-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=10000, max_digits=7)),
                ('marc', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('n_doors', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('6', '5')], default='4', max_length=32)),
                ('colors', models.CharField(choices=[('1', 'black'), ('2', 'blue'), ('3', 'white'), ('4', 'red'), ('5', 'grey'), ('6', 'yellow')], default='1', max_length=32)),
                ('age', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
