# Generated by Django 3.1.3 on 2020-11-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colors',
            field=models.CharField(choices=[('black', 'black'), ('blue', 'blue'), ('white', 'white'), ('red', 'red'), ('grey', 'grey'), ('yellow', 'yellow')], default='black', max_length=32),
        ),
    ]
